baseurl = "/"
languageCode = "pt-br"
title = "CEPESPData"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	# General information
	author = "CEPESP-FGV"
	description = "Guia para acessar os dados eleitorais do CEPESPData"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/GV-CEPESP/workshopR"

	version = ""
	logo = "logo_cepesp.jpg"
	favicon = "fgv_favicon"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	github   = "GV-CEPESP"
	email    = "cepesp@fgv.br"
	facebook = "cepesp.fgv"
	twitter  = "cepesp"
	
[[menu.main]]
	name   = "Acessando o CEPESPData"
	url    = "workshop/"
	weight = 5
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
